name: stargatenow
recipe: drupal9
config:
  webroot: web
  php: '7.4'
  composer_version: '2.1.6'
  xdebug: true
  cache: false
  via: apache
  database: mariadb
proxy:
  mailhog:
    - mail.stargatenow.lndo.site
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
#  chromedriver:
#    type: compose
#    services:
#      image: 'robcherry/docker-chromedriver:latest'
#      expose:
#        - '4444'
#      environment:
#        CHROMEDRIVER_WHITELISTED_IPS: ''
#        CHROMEDRIVER_URL_BASE: /wd/hub
#      security_opt:
#        - 'seccomp:unconfined'
#      command:
#        - /usr/local/bin/supervisord
#        - '-c'
#        - /etc/supervisord.conf
# tooling:
#  behat:
#    service: appserver
#    description: Run behat tests locally.
#    cmd:
#      - /app/vendor/bin/behat
#  drush:
#    cmd:
#      - /app/vendor/bin/drush
#      - '--root=/app/web'
#  drupal:
#    cmd:
#      - /app/vendor/bin/drupal
#      - '--root=/app/web'
